name: Hello world
on:
  # push:
  #   branches: main
  push:
    tags:
      - "*"
  issues:
    types: [opened]

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run bash script
        run: ./scripts/sample.sh
        shell: bash
