name: Hello world
on:
  # push:
  #   branches: main
  push:
    tags:
      - "*"
  issues:
    types: [opened,edited]

permissions:
  contents: write
  
jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run bash script
        run: |
          chmod +x ./scripts/sample.sh
          ./scripts/sample.sh
        shell: bash
        env:
          REPO: ${{ github.event.repository.name }}
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: build/*
